Repository manito42/backend, pull requests merged in 2023-08, with the labels that each got.

#17 update: #16 mentorProfile, user schema 변경
  api-docs.yml
  prisma/schema.prisma
  src/common/interfaces/api/mentorProfile/mentorProfileResponse.interface.ts
  src/common/interfaces/api/user/userRequest.interface.ts
  src/common/interfaces/api/user/userResponse.interface.ts
  src/database/factories/mentorProfile.factory.ts
  src/database/factories/user.factory.ts
  src/database/seeders/seeder.class.ts
  src/models/mentorProfile/dto/request/mentorProfileUpdatePayload.dto.ts
  src/models/mentorProfile/dto/response/mentorProfileGetResponse.dto.ts
  src/models/mentorProfile/mentorProfile.controller.ts
  src/models/mentorProfile/mentorProfile.service.ts
  src/models/mentorProfile/queries/mentorProfileSelect.query.ts
  src/models/reservation/reservation.controller.ts
  src/models/user/dto/response/userGetResponse.dto.ts
  src/models/user/queries/userSelect.query.ts
  src/models/user/user.service.ts
Labels: fix

#23 :bricks: chore: SonarQube
  .github/workflows/build.yml
  .github/workflows/nestjs-ci.yml
Labels: enhancement

#24 fix: sonarQube
  sonar-project.properties
Labels: enhancement, fix

#37 Feature/reservation
  api-docs.yml
  e2e/app.e2e-spec.ts
  e2e/jest-e2e.json
  e2e/reservation/reservation.e2e-spec.ts
  e2e/testSeed.ts
  package-lock.json
  package.json
  prisma/migrations/20230825104645_/migration.sql
  prisma/schema.prisma
  readme.md
  src/database/repository/reservation.repository.ts
  src/database/services/prisma.service.ts
  src/models/reservation/reservation.controller.ts
  src/models/reservation/reservation.module.ts
  src/models/reservation/reservation.service.ts
  src/models/user/user.service.ts
  src/modules/dev/dev.controller.ts
  tsconfig.build.json
Labels: feature

#39 :memo: [Docs]: update readme.md
  readme.md
Labels: documentation

#40 [Feat] : mail 을 통한 notification
  .gitignore
  env.sample
  package-lock.json
  package.json
  src/app.module.ts
  src/common/constants/getMailerConfig.ts
  src/common/decorators/OnSafeEvent.decorator.ts
  src/common/interfaces/event/reservation/reservationEventPayload.interface.ts
  src/database/seeders/jestSeeder.ts
  src/models/reservation/reservation.module.ts
  src/models/reservation/reservation.service.ts
  src/modules/notification/notification.controller.spec.ts
  src/modules/notification/notification.controller.ts
  src/modules/notification/notification.module.ts
  src/modules/notification/notification.service.ts
  src/modules/notification/templates/baseMail.template.ts
  src/modules/notification/templates/reservation/accept.template.ts
  src/modules/notification/templates/reservation/cancel.template.ts
  src/modules/notification/templates/reservation/menteeCompletion.template.ts
  src/modules/notification/templates/reservation/reqeust.template.ts
Labels: enhancement, feature

#43 Fix/build
  .github/scripts/startServer.sh
  .github/workflows/build_test.yml
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
  Dockerfile
  prisma/schema.prisma
Labels: fix

#49 Refactor/reservation
  src/app.module.ts
  src/common/constants/notification.event.ts
  src/database/repository/reservation.repository.ts
  src/database/services/prisma.service.ts
  src/models/hashtag/dto/request/hashtagCreatePayload.dto.ts
  src/models/reservation/reservation.controller.ts
  src/models/reservation/reservation.module.ts
  src/models/reservation/reservation.service.ts
  src/modules/notification/notification.controller.ts
  src/modules/notification/notification.module.ts
Labels: refactor

#53 [Refactor] #52 - User, MentorProfile, Hashtag
  api-docs.yml
  src/app.controller.spec.ts
  src/common/constants/selectAll.type.ts
  src/database/repository/hashtag.repository.ts
  src/database/repository/mentorProfile.repository.ts
  src/database/repository/user.repository.ts
  src/models/hashtag/hashtag.controller.spec.ts
  src/models/hashtag/hashtag.controller.ts
  src/models/hashtag/hashtag.module.ts
  src/models/hashtag/hashtag.service.spec.ts
  src/models/hashtag/hashtag.service.ts
  src/models/mentorProfile/dto/request/mentorProfileQuery.dto.ts
  src/models/mentorProfile/mentorProfile.controller.spec.ts
  src/models/mentorProfile/mentorProfile.controller.ts
  src/models/mentorProfile/mentorProfile.module.ts
  src/models/mentorProfile/mentorProfile.service.spec.ts
  src/models/mentorProfile/mentorProfile.service.ts
  src/models/mentorProfile/queries/getMentorProfilesWhereQuery.ts
  src/models/user/user.controller.spec.ts
  src/models/user/user.controller.ts
  src/models/user/user.module.ts
  src/models/user/user.service.spec.ts
  src/models/user/user.service.ts
  src/modules/auth/auth.controller.spec.ts
  src/modules/auth/auth.service.spec.ts
  src/modules/home/home.controller.spec.ts
  src/modules/home/home.controller.ts
  src/modules/home/home.service.spec.ts
  src/modules/search/search.controller.spec.ts
  src/modules/search/search.controller.ts
Labels: refactor

#54 Refactor/repository-category,feedback
  .github/workflows/build_test.yml
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
  prisma/schema.prisma
  src/database/repository/category.repository.ts
  src/database/repository/menteeFeedback.repository.ts
  src/database/repository/mentorFeedback.repository.ts
  src/database/repository/reservation.repository.ts
  src/models/category/category.controller.spec.ts
  src/models/category/category.module.ts
  src/models/category/category.service.spec.ts
  src/models/category/category.service.ts
  src/models/menteeFeedback/dto/request/menteeFeedbackQuery.dto.ts
  src/models/menteeFeedback/menteeFeedback.controller.spec.ts
  src/models/menteeFeedback/menteeFeedback.controller.ts
  src/models/menteeFeedback/menteeFeedback.module.ts
  src/models/menteeFeedback/menteeFeedback.service.spec.ts
  src/models/menteeFeedback/menteeFeedback.service.ts
  src/models/menteeFeedback/queries/getMenteeFeedbacksWhereQuery.ts
  src/models/mentorFeedback/dto/request/mentorFeedbackQuery.dto.ts
  src/models/mentorFeedback/mentorFeedback.controller.spec.ts
  src/models/mentorFeedback/mentorFeedback.controller.ts
  src/models/mentorFeedback/mentorFeedback.module.ts
  src/models/mentorFeedback/mentorFeedback.service.spec.ts
  src/models/mentorFeedback/mentorFeedback.service.ts
  src/models/mentorFeedback/queries/getMentorFeedbacksWhereQuery.ts
  src/models/mentorProfile/dto/request/mentorProfileQuery.dto.ts
  src/models/reservation/dto/request/reservationQuery.dto.ts
  src/models/reservation/queries/getReservationsWhereQuery.ts
  src/models/reservation/reservation.controller.spec.ts
  src/models/reservation/reservation.controller.ts
  src/models/reservation/reservation.module.ts
  src/models/reservation/reservation.service.spec.ts
  src/models/reservation/reservation.service.ts
Labels: fix, refactor

#63 :bug: [Fix]: mail
  e2e/reservation/reservation.e2e-spec.ts
  src/app.module.ts
  src/models/reservation/reservation.module.ts
Labels: fix

#62 🐛 [Fix]: SelectAllType Default 설정으로 인한 오류 해결
  src/common/decorators/isBooleanSelectAll.decorator.ts
  src/common/decorators/isIntSelectAll.decorator.ts
  src/models/menteeFeedback/dto/request/menteeFeedbackQuery.dto.ts
  src/models/mentorFeedback/dto/request/mentorFeedbackQuery.dto.ts
  src/models/mentorProfile/dto/request/mentorProfileQuery.dto.ts
  src/models/reservation/dto/request/reservationQuery.dto.ts
Labels: fix

#64 :bug: [Fix]: remove pm2 logs
  package.json
Labels: fix
