Repository manito42/backend, pull requests merged in 2023-09, with the labels that each got.

#67 :white_check_mark: [Test]: mentor profile description e2e test
  e2e/mentorProfile/mentorProfile-Update.e2e-spec.ts
Labels: test

#68 :construction_worker: [Refactor]: CI script update
  .github/workflows/build_test.yml
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
Labels: enhancement

#72 Feat/reservation checked
  .github/workflows/build_test.yml
  api-docs.yml
  e2e/jest-e2e.json
  e2e/reservation/reservation.e2e-spec.ts
  prisma/migrations/20230905050509_mentee_checked/migration.sql
  prisma/schema.prisma
  src/database/repository/reservation.repository.ts
  src/models/reservation/reservation.controller.ts
  src/models/reservation/reservation.service.ts
Labels: enhancement, feature

#74 ✨ [Feat]: 카테고리를 통한 검색 기능 추가
  api-docs.yml
  src/database/repository/mentorProfile.repository.ts
  src/models/mentorProfile/mentorProfile.service.ts
  src/models/mentorProfile/queries/getMentorProfilesWhereQuery.ts
  src/modules/search/dto/request/searchQuery.dto.ts
  src/modules/search/search.controller.ts
Labels: enhancement

#77 :memo: [Fix] swagger auth
  api-docs.yml
Labels: bug

#79 :sparkles: [Feat]: users/id/reservations/request
  api-docs.yml
  src/common/interfaces/api/reservation/reservationResponse.interface.ts
  src/database/repository/user.repository.ts
  src/models/reservation/dto/response/reservationGetResponse.dto.ts
  src/models/reservation/queries/reservationSelect.query.ts
  src/models/user/user.controller.ts
  src/models/user/user.service.ts
Labels: enhancement

#82 Feat/pagination
  .github/scripts/startServer.sh
  Dockerfile
  api-docs.yml
  docker-compose.dev-server.yml
  docker-compose.yml
  k6/test.js
  prisma_init.sh
  seeder.sh
  src/common/interfaces/api/common/IPaginationResponse.interface.ts
  src/common/interfaces/api/common/PaginationInfoDto.interface.ts
  src/database/repository/hashtag.repository.ts
  src/database/repository/menteeFeedback.repository.ts
  src/database/repository/mentorFeedback.repository.ts
  src/database/repository/mentorProfile.repository.ts
  src/database/repository/reservation.repository.ts
  src/database/repository/user.repository.ts
  src/models/hashtag/dto/response/hashtagPaginationResponse.dto.ts
  src/models/hashtag/hashtag.controller.ts
  src/models/hashtag/hashtag.service.ts
  src/models/menteeFeedback/dto/response/menteeFeedbackPaginationResponse.dto.ts
  src/models/menteeFeedback/menteeFeedback.controller.ts
  src/models/menteeFeedback/menteeFeedback.service.ts
  src/models/mentorFeedback/dto/response/mentorFeedbackPaginationResponse.dto.ts
  src/models/mentorFeedback/mentorFeedback.controller.ts
  src/models/mentorFeedback/mentorFeedback.service.ts
  src/models/mentorProfile/dto/response/mentorProfilePaginationResponse.dto.ts
  src/models/mentorProfile/mentorProfile.controller.ts
  src/models/mentorProfile/mentorProfile.service.ts
  src/models/reservation/dto/response/reservationPaginationResponse.dto.ts
  src/models/reservation/reservation.controller.ts
  src/models/reservation/reservation.service.ts
  src/models/user/dto/request/userReservationQuery.dto.ts
  src/models/user/dto/response/userReservationPaginationResponse.dto.ts
  src/models/user/queries/userReservationWhere.query.ts
  src/models/user/user.controller.ts
  src/models/user/user.service.ts
  src/modules/home/home.controller.ts
  src/modules/home/home.service.ts
  start.sh
Labels: feature

#85 :bug: [Fix] Deploy 과정에서 migration 오류가 나는 문제를 해결함.
  .github/scripts/startServer.sh
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
Labels: fix, emergency

#86 [Update] User Reservation API 변경
  api-docs.yml
  src/common/enums/ReservationRole.enum.ts
  src/common/enums/index.ts
  src/database/repository/user.repository.ts
  src/models/user/dto/request/userReservationQuery.dto.ts
  src/models/user/queries/userReservationWhere.query.ts
  src/models/user/user.controller.ts
  src/models/user/user.service.ts
Labels: enhancement, fix, emergency

#87 :rocket: [Fix]: change s3 upload command
  .github/workflows/dev-deploy.yml
  .github/workflows/manual-trigger.yml
  .github/workflows/prod-deploy.yml
Labels: fix

#91 [Fix] user reservation query
  src/models/user/queries/userReservationWhere.query.ts
  src/modules/home/home.module.ts
  src/modules/search/search.module.ts
Labels: bug

#96 Feature/change profile description#95
  .dockerignore
  api-docs.yml
  e2e/mentorProfile/mentorProfile-Update.e2e-spec.ts
  prisma/migrations/20230918024610_95/migration.sql
  prisma/schema.prisma
  src/database/factories/category.factory.ts
  src/database/repository/user.repository.ts
  src/models/mentorProfile/dto/request/mentorProfileUpdatePayload.dto.ts
  src/models/mentorProfile/mentorProfile.controller.ts
Labels: enhancement, feature

#99 Feature/remove home service random #93
  src/modules/home/home.controller.ts
  src/modules/home/home.service.ts
Labels: enhancement, fix, feature

#105 Fix/mentor feedback
  Dockerfile
  seeder.sh
  src/database/repository/reservation.repository.ts
Labels: fix

#107 Fix/rating
  e2e/reservation/reservation.e2e-spec.ts
  src/database/repository/reservation.repository.ts
  start.sh
Labels: fix

#108 Fix/dockerfile
  Dockerfile
  docker-compose.yml
  env.sample
Labels: fix

#111 Fix/email template
  src/modules/notification/notification.controller.ts
  src/modules/notification/templates/baseMail.template.ts
  src/modules/notification/templates/reservation/accept.template.ts
  src/modules/notification/templates/reservation/cancel.template.ts
  src/modules/notification/templates/reservation/menteeCompletion.template.ts
  src/modules/notification/templates/reservation/reqeust.template.ts
Labels: feature

#115 Fix/reservation category#113
  .dockerignore
  e2e/reservation/reservation.e2e-spec.ts
  src/database/repository/reservation.repository.ts
Labels: fix

#119 116 feature 멘토링 취소 사유 추가
  api-docs.yml
  e2e/reservation/reservation.e2e-spec.ts
  prisma/migrations/20230928063148_116/migration.sql
  prisma/schema.prisma
  src/common/interfaces/api/cancelReason/cancelReasonResponse.interface.ts
  src/common/interfaces/api/reservation/reservationResponse.interface.ts
  src/common/interfaces/event/reservation/reservationEventPayload.interface.ts
  src/config/ft/config.module.ts
  src/config/jwt/config.module.ts
  src/database/repository/reservation.repository.ts
  src/database/services/prisma.module.ts
  src/models/category/category.module.ts
  src/models/hashtag/hashtag.module.ts
  src/models/menteeFeedback/menteeFeedback.module.ts
  src/models/mentorFeedback/mentorFeedback.module.ts
  src/models/mentorProfile/mentorProfile.module.ts
  src/models/reservation/dto/request/reservationUpdatePayload.dto.ts
  src/models/reservation/dto/response/reservationGetResponse.dto.ts
  src/models/reservation/queries/reservationSelect.query.ts
  src/models/reservation/reservation.controller.ts
  src/models/reservation/reservation.module.ts
  src/models/reservation/reservation.service.ts
  src/models/user/user.module.ts
  src/modules/auth/auth.module.ts
  src/modules/home/home.controller.ts
  src/modules/home/home.module.ts
  src/modules/notification/notification.controller.ts
  src/modules/notification/notification.service.ts
  src/modules/notification/templates/reservation/accept.template.ts
  src/modules/notification/templates/reservation/cancel.template.ts
  src/modules/notification/templates/reservation/menteeCompletion.template.ts
  src/modules/notification/templates/reservation/reqeust.template.ts
  src/modules/search/search.module.ts
Labels: enhancement, todo, feature, refactor

#120 Feature/improve dev module 117
  src/app.module.ts
  src/modules/auth/auth.dynamic.module.ts
  src/modules/dev/dev.controller.ts
  src/modules/dev/dev.module.ts
  src/modules/dev/dev.service.ts
Labels: enhancement, feature
