Repository manito42/backend, pull requests merged in 2023-10, with the labels that each got.

#122 121 fix mentorprofileupdate validation 추가
  e2e/mentorProfile/mentorProfile-Update.e2e-spec.ts
  src/models/mentorProfile/mentorProfile.controller.ts
  src/models/mentorProfile/mentorProfile.service.ts
  src/modules/auth/auth.dynamic.module.ts
Labels: bug

#123 226 todo 멘토링 확인 프로세스 변경
  api-docs.yml
  e2e/mentorProfile/mentorProfile-Update.e2e-spec.ts
  prisma/migrations/20231001110315_226/migration.sql
  prisma/schema.prisma
  src/common/interfaces/api/mentorProfile/mentorProfileRequest.interface.ts
  src/database/repository/mentorProfile.repository.ts
  src/database/repository/user.repository.ts
  src/models/mentorProfile/dto/request/mentorProfileUpdatePayload.dto.ts
  src/models/mentorProfile/dto/response/mentorProfileGetResponse.dto.ts
  src/models/mentorProfile/mentorProfile.controller.ts
  src/models/mentorProfile/mentorProfile.service.ts
  src/models/mentorProfile/queries/mentorProfileSelect.query.ts
Labels: feature

#124 :sparkles: [Feat]: reservation 생성 조건 변경
  prisma/migrations/20231001120336_118/migration.sql
  prisma/schema.prisma
  src/database/repository/reservation.repository.ts
Labels: fix

#131 Refactor/mentor profile update
  .github/workflows/deploy-api-docs.yml
  api-docs.yml
  prisma/migrations/20231005163230_disable_null_social_link/migration.sql
  prisma/schema.prisma
  src/database/repository/mentorProfile.repository.ts
  src/models/mentorProfile/dto/request/mentorProfileActivate.dto.ts
  src/models/mentorProfile/dto/request/mentorProfileUpdatePayload.dto.ts
  src/models/mentorProfile/mentorProfile.controller.ts
  src/models/mentorProfile/mentorProfile.service.ts
Labels: feature

#132 [Fix] reservation mail
  src/modules/notification/templates/baseMail.template.ts
  src/modules/notification/templates/reservation/accept.template.ts
Labels: fix

#141 Feat/socialink optional #139
  api-docs.yml
  src/database/repository/mentorProfile.repository.ts
Labels: feature

#143 ✨ [Feat]: 멘토링 진행요건 완화
  src/database/repository/reservation.repository.ts
Labels: feature

#145 🐛 [Fix] socialLink
  src/database/repository/mentorProfile.repository.ts
Labels: bug, fix

#146 Ver 1.0.1
  api-docs.yml
  src/database/repository/mentorProfile.repository.ts
  src/database/repository/reservation.repository.ts
  src/database/repository/user.repository.ts
  src/models/user/user.service.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
  src/modules/dev/dev.controller.ts
  src/modules/dev/dev.module.ts
  src/modules/dev/dev.service.ts
Labels: release
